name: Check and Test

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env

      - name: Pre-commit check
        run: uv run pre-commit run -a --show-diff-on-failure --color=always

      - name: Check for type errors
        run: uv run mypy


      - name: Check for obsolete dependencies
        run: uv run deptry .


  tests-on-multiple-python-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          "3.10", "3.11", "3.12", "3.13"
        ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest tests


  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check if documentation can be built
        run: uv run mkdocs build -s
