name: Pre-release and Hotfix

on:
  push:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  bump-version-and-changelog:
    name: Bump version and generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_sha: ${{ steps.get-sha.outputs.sha }}
    # Skip this job if the commit message starts with 'bump:' as it's already a bump commit
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          uv-version: "0.6.16"

      - name: Check if nothing to bump
        id: check_bump
        run: |
          next_version=$(uv run cz bump --get-next --yes)
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
          if [ -z "$next_version" ]; then
            exit 1
          fi
        continue-on-error: true

      - name: Check if tag exists
        id: check_tag
        if: ${{ steps.check_bump.outcome == 'success' }}
        run: |
          tag_exists=$(git tag -l v${{ steps.check_bump.outputs.next_version }})
          echo "tag_exists=$tag_exists" >> $GITHUB_OUTPUT
          if [ -n "$tag_exists" ]; then
            exit 1
          fi

      - name: Bump version and generate changelog
        id: bump
        if: ${{ steps.check_tag.outcome == 'success' }}
        uses: commitizen-tools/commitizen-action@master
        with:
          commit: true
          push: false
          no_raise: null

      - name: push bump commit
        if: ${{ steps.bump.outcome == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_ACCESS_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get the new commit SHA
        if: ${{ steps.bump.outcome == 'success' }}
        id: get-sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  release-draft:
    runs-on: ubuntu-latest
    needs: bump-version-and-changelog
    permissions:
      contents: write
    steps:
      - name: Get the new commit SHA
        id: get_new_sha
        # if there is no new commit, exit 1
        run: |
          if [ -z "${{ needs.bump-version-and-changelog.outputs.new_sha }}" ]; then
            echo "No new commit found."
            exit 1
          else
            echo "sha=${{ needs.bump-version-and-changelog.outputs.new_sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.get_new_sha.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env

      - name: Build package
        run: uv build

      - name: Get version from pyproject.toml
        id: get_version
        run: echo "version=$(grep -oP '^version\s*=\s"\K[^"]+' pyproject.toml)" >> $GITHUB_OUTPUT

      - name: Create release draft
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          body_path: CHANGELOG.md
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: true
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
