name: Release

on:
  push:
    branches:
      - main

jobs:
  check-version:
    name: Check the version consistency
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from pyproject.toml
        id: get_version
        run: grep -oP '^version\s*=\s"\K[^"]+' pyproject.toml

      - name: Check version
        # The tag should be in the form "vX.Y.Z", the output of the previous step should be "X.Y.Z"
        run: |
          if [[ v${{ steps.get_version.outputs.version }} != ${{ github.ref_name }} ]]; then
            echo "Version mismatch: ${{ github.ref_name }} != ${{ steps.get_version.outputs.version }}"
            exit 1
          fi

  build-sdists-and-wheels:
    name: Build sdists and wheels
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env

      - name: Build sdist
        run: uv build --sdist

      - name: Build wheels
        run: uv build --wheel

      - name: Upload sdists and wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: build-sdists-and-wheels
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Build documentation
        run: uv run mkdocs build

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  release-to-github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build-sdists-and-wheels
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download sdists and wheels
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: false

  publish-to-pypi:
    name: Publish to PyPI
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    needs: build-sdists-and-wheels

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Download sdists and wheels
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish to PyPI
        run: uv publish --index testpypi --trusted-publishing
